export const menuItems = [
  {
    id: 1,
    img: "./menuAssets/main/macNcheese.jpg",
    name: "Baked Macaroni And Cheese",
    price: "20",
    type: "Main",
  },
  {
    id: 2,
    img: "./menuAssets/appetizers/chipotleShrimp.jpg",
    name: "Chipotle Shrimp",
    price: "4.50",
    type: "Appetizers",
  },
  {
    id: 3,
    img: "./menuAssets/specials/tamWorthChop.webp",
    name: "Tam Worth Chop",
    price: "52.50",
    type: "Specials",
    desc: "Our Tamworth chop is a juicy and flavorful cut of pork with a perfect balance of tenderness and texture.",
  },
  {
    id: 4,
    img: "./menuAssets/main/bakedZiti.jpg",
    name: "Baked Ziti",
    price: "16.50",
    type: "Main",
  },
  {
    id: 5,
    img: "./menuAssets/appetizers/grilledFlatbread.jpg",
    name: "Grilled Flatbread",
    price: "8.50",
    type: "Appetizers",
  },
  {
    id: 6,
    img: "./menuAssets/specials/slowRoastedLamb.webp",
    name: "Slow Roasted Lamb",
    price: "70",
    type: "Specials",
    desc: "Our slow roasted lamb is tender, succulent, and bursting with savory flavor that melts in your mouth.",
  },
  {
    id: 7,
    img: "./menuAssets/main/meatLoaf.jpg",
    name: "Meatloaf",
    price: "18",
    type: "Main",
  },
  {
    id: 8,
    img: "./menuAssets/appetizers/honeyBrie.jpg",
    name: "Honey Brie",
    price: "7.50",
    type: "Appetizers",
  },
  {
    id: 9,
    img: "./menuAssets/specials/roastDuck.webp",
    name: "Roasted Duck",
    price: "42",
    type: "Specials",
    desc: "Our roasted duck is a crispy and succulent delight, bursting with rich, savory flavor that will tantalize your taste buds.",
  },
  {
    id: 10,
    img: "./menuAssets/main/onePotChicken.webp",
    name: "One Pot Chicken",
    price: "22",
    type: "Main",
  },
  {
    id: 11,
    img: "./menuAssets/appetizers/taterTots.jpg",
    name: "Tater Tots",
    price: "9",
    type: "Appetizers",
  },
  {
    id: 12,
    img: "./menuAssets/specials/kobeRib.jpg",
    name: "Kobe Rib",
    price: "45",
    type: "Specials",
    desc: "Our Kobe rib is a tender and flavorful cut of beef with intricate marbling, delivering a melt-in-your-mouth experience that is sure to satisfy even the most discerning palates.",
  },
  {
    id: 13,
    img: "./menuAssets/specials/BakedLobster.webp",
    name: "Baked Stuffed Lobster",
    price: "70",
    type: "Specials",
    desc: "Our baked lobster is a mouth-watering dish that combines succulent and sweet meat with a golden, buttery topping, creating a delightful texture and flavor that will leave you wanting more.",
  },
  {
    id: 14,
    img: "./menuAssets/specials/crabCakes.webp",
    name: "Crab Cakes",
    price: "30",
    type: "Specials",
    desc: "Our crab cakes are a delectable combination of fresh, juicy crab meat, savory seasonings, and a golden crispy coating, offering a taste of the ocean in every bite.",
  },
];
